name: Deploy

on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build_image
        run: |
          docker build -t yaoa/docker-aria2-with-webui:build -f ./Dockerfile .
          export IMAGE_ID_TEMP=$(sudo docker images --filter=reference=yaoa/docker-aria2-with-webui:build --format "{{.ID}}")
          echo "##[set-output name=image_id;]$IMAGE_ID_TEMP"
      - name: Login
        env:
          dockerID: ${{ secrets.dockerID }}
          dockerPassword: ${{ secrets.dockerPassword }}
        run: |
          docker login -u $dockerID -p $dockerPassword
      - name: Deploy Commit ID
        if: ${{ github.head_ref == '' && github.sha != '' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/docker-aria2-with-webui:$GITHUB_SHA
          docker push yaoa/docker-aria2-with-webui:$GITHUB_SHA
      - name: Deploy Latest
        if: ${{ github.head_ref == '' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/docker-aria2-with-webui:latest
          docker push yaoa/docker-aria2-with-webui:latest
      - name: Deploy Nightly
        if: ${{ github.head_ref == '' && github.ref == 'refs/heads/master' && github.event_name == 'schedule' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/docker-aria2-with-webui:nightly
          docker push yaoa/docker-aria2-with-webui:nightly
      - name: Deploy Run Number
        if: ${{ github.head_ref == '' && github.sha != '' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/docker-aria2-with-webui:$GITHUB_RUN_NUMBER
          docker push yaoa/docker-aria2-with-webui:$GITHUB_RUN_NUMBER
      - name: Deploy Develop
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/dev') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/docker-aria2-with-webui:latest-develop
          docker push yaoa/docker-aria2-with-webui:latest-develop
      - name: Deploy Branch
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/') && github.event_name == 'push' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/docker-aria2-with-webui:${GITHUB_REF##*/}
          docker push yaoa/docker-aria2-with-webui:${GITHUB_REF##*/}
      - name: Deploy Tag
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/tags/') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/docker-aria2-with-webui:${GITHUB_REF##*/}
          docker push yaoa/docker-aria2-with-webui:${GITHUB_REF##*/}
